version: '2'
services:
  sample-mysql:
    image: mysql:5.6.35
    environment:
      - MYSQL_ROOT_PASSWORD=sample
    volumes:
    - ./docker/sample-mysql/data:/var/lib/mysql
    ports:
    - "3306:3306"
  sample-web:
    build:
      context: .
      dockerfile: ./docker/sample-web/Dockerfile
    environment:
      - BOOTSTRAP=false
      - RAILS_ENV=staging
    command: ./docker/sample-web/run.sh
    volumes:
      - .:/sample
    ports:
      - "3000:3000"
    depends_on:
      - sample-mysql
